// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_8RyQVTxd5s8OUZIQdDJeQjJJ1A8ePtc',
    appId: '1:485891287317:web:e661ddfb1510b5d5ade11c',
    messagingSenderId: '485891287317',
    projectId: 'express-b2e39',
    authDomain: 'express-b2e39.firebaseapp.com',
    storageBucket: 'express-b2e39.firebasestorage.app',
    measurementId: 'G-FSM69JBTMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALM5t_qZd-vMgGF-5HAlFeNO9jkP2DXw',
    appId: '1:485891287317:android:6ca70fcd159dca65ade11c',
    messagingSenderId: '485891287317',
    projectId: 'express-b2e39',
    storageBucket: 'express-b2e39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClD57SxWFuCcV3Fep2r6zVHi1mYo-QWww',
    appId: '1:485891287317:ios:df4f9e404af4d4a4ade11c',
    messagingSenderId: '485891287317',
    projectId: 'express-b2e39',
    storageBucket: 'express-b2e39.firebasestorage.app',
    iosBundleId: 'com.example.express',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClD57SxWFuCcV3Fep2r6zVHi1mYo-QWww',
    appId: '1:485891287317:ios:df4f9e404af4d4a4ade11c',
    messagingSenderId: '485891287317',
    projectId: 'express-b2e39',
    storageBucket: 'express-b2e39.firebasestorage.app',
    iosBundleId: 'com.example.express',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_8RyQVTxd5s8OUZIQdDJeQjJJ1A8ePtc',
    appId: '1:485891287317:web:89c817273f643716ade11c',
    messagingSenderId: '485891287317',
    projectId: 'express-b2e39',
    authDomain: 'express-b2e39.firebaseapp.com',
    storageBucket: 'express-b2e39.firebasestorage.app',
    measurementId: 'G-487CT4NM5H',
  );
}
